#define HAVE_LIBPNG
#define PATHSEPARATOR ";"
#define DEFAULT_FONTPATH "C:\\WINDOWS\\FONTS"
#define HAVE_FT2BUILD_H
#define HAVE_LIBZ
#define HAVE_GD_BUNDLED 1
#define HAVE_GD_GIF_READ 1
#define HAVE_GD_GIF_CREATE 1
#define HAVE_GD_IMAGESETBRUSH 1
#define HAVE_GD_IMAGESETTILE 1
#define HAVE_GD_JPG
#define HAVE_GD_PNG
#define HAVE_GD_STRINGFTEX 1
#define HAVE_GD_STRINGTTF 1
#define HAVE_GD_XBM
#define HAVE_LIBFREETYPE 1
#define HAVE_LIBJPEG
#define HAVE_LIBPNG
#define USE_GD_IMGSTRTTF
