#ifndef __COMBINEDKEYS_H
#define __COMBINEDKEYS_H

#define VK_CTRL_F1	(VK_F1  | (PKF_CONTROL << 16))
#define VK_CTRL_F2	(VK_F2  | (PKF_CONTROL << 16))
#define VK_CTRL_F3	(VK_F3  | (PKF_CONTROL << 16))
#define VK_CTRL_F4	(VK_F4  | (PKF_CONTROL << 16))
#define VK_CTRL_F5	(VK_F5  | (PKF_CONTROL << 16))
#define VK_CTRL_F6	(VK_F6  | (PKF_CONTROL << 16))
#define VK_CTRL_F7	(VK_F7  | (PKF_CONTROL << 16))
#define VK_CTRL_F8	(VK_F8  | (PKF_CONTROL << 16))
#define VK_CTRL_F9	(VK_F9  | (PKF_CONTROL << 16))
#define VK_CTRL_F10	(VK_F10 | (PKF_CONTROL << 16))
#define VK_CTRL_F11	(VK_F11 | (PKF_CONTROL << 16))
#define VK_CTRL_F12	(VK_F12 | (PKF_CONTROL << 16))
#define VK_CTRL_UP			(VK_UP       | (PKF_CONTROL << 16))
#define VK_CTRL_DOWN		(VK_DOWN     | (PKF_CONTROL << 16))
#define VK_CTRL_LEFT		(VK_LEFT     | (PKF_CONTROL << 16))
#define VK_CTRL_RIGHT		(VK_RIGHT    | (PKF_CONTROL << 16))
#define VK_CTRL_RETURN		(VK_RETURN   | (PKF_CONTROL << 16))
#define VK_CTRL_ADD			(VK_ADD      | (PKF_CONTROL << 16))
#define VK_CTRL_SUBTRACT	(VK_SUBTRACT | (PKF_CONTROL << 16))
#define VK_CTRL_DIVIDE		(VK_DIVIDE   | (PKF_CONTROL << 16))
#define VK_CTRL_MULTIPLY	(VK_MULTIPLY | (PKF_CONTROL << 16))

#define VK_ALT_F1	(VK_F1  | (PKF_ALT << 16))
#define VK_ALT_F2	(VK_F2  | (PKF_ALT << 16))
#define VK_ALT_F3	(VK_F3  | (PKF_ALT << 16))
#define VK_ALT_F4	(VK_F4  | (PKF_ALT << 16))
#define VK_ALT_F5	(VK_F5  | (PKF_ALT << 16))
#define VK_ALT_F6	(VK_F6  | (PKF_ALT << 16))
#define VK_ALT_F7	(VK_F7  | (PKF_ALT << 16))
#define VK_ALT_F8	(VK_F8  | (PKF_ALT << 16))
#define VK_ALT_F9	(VK_F9  | (PKF_ALT << 16))
#define VK_ALT_F10	(VK_F10 | (PKF_ALT << 16))
#define VK_ALT_F11	(VK_F11 | (PKF_ALT << 16))
#define VK_ALT_F12	(VK_F12 | (PKF_ALT << 16))
#define VK_ALT_UP			(VK_UP       | (PKF_ALT << 16))
#define VK_ALT_DOWN			(VK_DOWN     | (PKF_ALT << 16))
#define VK_ALT_LEFT			(VK_LEFT     | (PKF_ALT << 16))
#define VK_ALT_RIGHT		(VK_RIGHT    | (PKF_ALT << 16))
#define VK_ALT_RETURN		(VK_RETURN   | (PKF_ALT << 16))
#define VK_ALT_ADD			(VK_ADD      | (PKF_ALT << 16))
#define VK_ALT_SUBTRACT		(VK_SUBTRACT | (PKF_ALT << 16))
#define VK_ALT_DIVIDE		(VK_DIVIDE   | (PKF_ALT << 16))
#define VK_ALT_MULTIPLY		(VK_MULTIPLY | (PKF_ALT << 16))

#define VK_SHIFT_F1		(VK_F1  | (PKF_SHIFT << 16))
#define VK_SHIFT_F2		(VK_F2  | (PKF_SHIFT << 16))
#define VK_SHIFT_F3		(VK_F3  | (PKF_SHIFT << 16))
#define VK_SHIFT_F4		(VK_F4  | (PKF_SHIFT << 16))
#define VK_SHIFT_F5		(VK_F5  | (PKF_SHIFT << 16))
#define VK_SHIFT_F6		(VK_F6  | (PKF_SHIFT << 16))
#define VK_SHIFT_F7		(VK_F7  | (PKF_SHIFT << 16))
#define VK_SHIFT_F8		(VK_F8  | (PKF_SHIFT << 16))
#define VK_SHIFT_F9		(VK_F9  | (PKF_SHIFT << 16))
#define VK_SHIFT_F10	(VK_F10 | (PKF_SHIFT << 16))
#define VK_SHIFT_F11	(VK_F11 | (PKF_SHIFT << 16))
#define VK_SHIFT_F12	(VK_F12 | (PKF_SHIFT << 16))
#define VK_SHIFT_UP			(VK_UP       | (PKF_SHIFT << 16))
#define VK_SHIFT_DOWN		(VK_DOWN     | (PKF_SHIFT << 16))
#define VK_SHIFT_LEFT		(VK_LEFT     | (PKF_SHIFT << 16))
#define VK_SHIFT_RIGHT		(VK_RIGHT    | (PKF_SHIFT << 16))
#define VK_SHIFT_RETURN		(VK_RETURN   | (PKF_SHIFT << 16))
#define VK_SHIFT_ADD		(VK_ADD      | (PKF_SHIFT << 16))
#define VK_SHIFT_SUBTRACT	(VK_SUBTRACT | (PKF_SHIFT << 16))
#define VK_SHIFT_DIVIDE		(VK_DIVIDE   | (PKF_SHIFT << 16))
#define VK_SHIFT_MULTIPLY	(VK_MULTIPLY | (PKF_SHIFT << 16))

#define VK_CTRL_ALT_RETURN	(VK_RETURN | ((PKF_CONTROL|PKF_ALT) << 16))

#endif
