#undef DECLARE_PERSIST_VARS
#undef DECLARE_PERSIST_LOAD
#undef DECLARE_PERSIST_SAVE

#undef PERSIST_BOOL_VARIABLE
#undef PERSIST_bool_VARIABLE
#undef PERSIST_STRING_VARIABLE
#undef PERSIST_TYPED_VARIABLE
#undef PERSIST_FILETIME_VARIABLE

#undef PERSIST_BOOL_VARIABLE_
#undef PERSIST_bool_VARIABLE_
#undef PERSIST_STRING_VARIABLE_
#undef PERSIST_TYPED_VARIABLE_
#undef PERSIST_FILETIME_VARIABLE_
